/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsCrmActRouteImport } from './routes/products.crm-act'
import { Route as AboutWhoWeAreRouteImport } from './routes/about.who-we-are'
import { Route as AboutVisionMissionRouteImport } from './routes/about.vision-mission'
import { Route as AboutOurJourneyRouteImport } from './routes/about.our-journey'
import { Route as AboutOurApproachRouteImport } from './routes/about.our-approach'
import { Route as AboutLeadershipFacilitatorsRouteImport } from './routes/about.leadership-facilitators'
import { Route as AboutCoreValuesRouteImport } from './routes/about.core-values'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCrmActRoute = ProductsCrmActRouteImport.update({
  id: '/crm-act',
  path: '/crm-act',
  getParentRoute: () => ProductsRoute,
} as any)
const AboutWhoWeAreRoute = AboutWhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => AboutRoute,
} as any)
const AboutVisionMissionRoute = AboutVisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => AboutRoute,
} as any)
const AboutOurJourneyRoute = AboutOurJourneyRouteImport.update({
  id: '/our-journey',
  path: '/our-journey',
  getParentRoute: () => AboutRoute,
} as any)
const AboutOurApproachRoute = AboutOurApproachRouteImport.update({
  id: '/our-approach',
  path: '/our-approach',
  getParentRoute: () => AboutRoute,
} as any)
const AboutLeadershipFacilitatorsRoute =
  AboutLeadershipFacilitatorsRouteImport.update({
    id: '/leadership-facilitators',
    path: '/leadership-facilitators',
    getParentRoute: () => AboutRoute,
  } as any)
const AboutCoreValuesRoute = AboutCoreValuesRouteImport.update({
  id: '/core-values',
  path: '/core-values',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/about/core-values': typeof AboutCoreValuesRoute
  '/about/leadership-facilitators': typeof AboutLeadershipFacilitatorsRoute
  '/about/our-approach': typeof AboutOurApproachRoute
  '/about/our-journey': typeof AboutOurJourneyRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/products/crm-act': typeof ProductsCrmActRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/about/core-values': typeof AboutCoreValuesRoute
  '/about/leadership-facilitators': typeof AboutLeadershipFacilitatorsRoute
  '/about/our-approach': typeof AboutOurApproachRoute
  '/about/our-journey': typeof AboutOurJourneyRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/products/crm-act': typeof ProductsCrmActRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/about/core-values': typeof AboutCoreValuesRoute
  '/about/leadership-facilitators': typeof AboutLeadershipFacilitatorsRoute
  '/about/our-approach': typeof AboutOurApproachRoute
  '/about/our-journey': typeof AboutOurJourneyRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/products/crm-act': typeof ProductsCrmActRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/impact'
    | '/insights'
    | '/privacy'
    | '/products'
    | '/programs'
    | '/services'
    | '/terms'
    | '/about/core-values'
    | '/about/leadership-facilitators'
    | '/about/our-approach'
    | '/about/our-journey'
    | '/about/vision-mission'
    | '/about/who-we-are'
    | '/products/crm-act'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/impact'
    | '/insights'
    | '/privacy'
    | '/products'
    | '/programs'
    | '/services'
    | '/terms'
    | '/about/core-values'
    | '/about/leadership-facilitators'
    | '/about/our-approach'
    | '/about/our-journey'
    | '/about/vision-mission'
    | '/about/who-we-are'
    | '/products/crm-act'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/impact'
    | '/insights'
    | '/privacy'
    | '/products'
    | '/programs'
    | '/services'
    | '/terms'
    | '/about/core-values'
    | '/about/leadership-facilitators'
    | '/about/our-approach'
    | '/about/our-journey'
    | '/about/vision-mission'
    | '/about/who-we-are'
    | '/products/crm-act'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  ImpactRoute: typeof ImpactRoute
  InsightsRoute: typeof InsightsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProgramsRoute: typeof ProgramsRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/crm-act': {
      id: '/products/crm-act'
      path: '/crm-act'
      fullPath: '/products/crm-act'
      preLoaderRoute: typeof ProductsCrmActRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/about/who-we-are': {
      id: '/about/who-we-are'
      path: '/who-we-are'
      fullPath: '/about/who-we-are'
      preLoaderRoute: typeof AboutWhoWeAreRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/vision-mission': {
      id: '/about/vision-mission'
      path: '/vision-mission'
      fullPath: '/about/vision-mission'
      preLoaderRoute: typeof AboutVisionMissionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/our-journey': {
      id: '/about/our-journey'
      path: '/our-journey'
      fullPath: '/about/our-journey'
      preLoaderRoute: typeof AboutOurJourneyRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/our-approach': {
      id: '/about/our-approach'
      path: '/our-approach'
      fullPath: '/about/our-approach'
      preLoaderRoute: typeof AboutOurApproachRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/leadership-facilitators': {
      id: '/about/leadership-facilitators'
      path: '/leadership-facilitators'
      fullPath: '/about/leadership-facilitators'
      preLoaderRoute: typeof AboutLeadershipFacilitatorsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/core-values': {
      id: '/about/core-values'
      path: '/core-values'
      fullPath: '/about/core-values'
      preLoaderRoute: typeof AboutCoreValuesRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutCoreValuesRoute: typeof AboutCoreValuesRoute
  AboutLeadershipFacilitatorsRoute: typeof AboutLeadershipFacilitatorsRoute
  AboutOurApproachRoute: typeof AboutOurApproachRoute
  AboutOurJourneyRoute: typeof AboutOurJourneyRoute
  AboutVisionMissionRoute: typeof AboutVisionMissionRoute
  AboutWhoWeAreRoute: typeof AboutWhoWeAreRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutCoreValuesRoute: AboutCoreValuesRoute,
  AboutLeadershipFacilitatorsRoute: AboutLeadershipFacilitatorsRoute,
  AboutOurApproachRoute: AboutOurApproachRoute,
  AboutOurJourneyRoute: AboutOurJourneyRoute,
  AboutVisionMissionRoute: AboutVisionMissionRoute,
  AboutWhoWeAreRoute: AboutWhoWeAreRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface ProductsRouteChildren {
  ProductsCrmActRoute: typeof ProductsCrmActRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCrmActRoute: ProductsCrmActRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  ImpactRoute: ImpactRoute,
  InsightsRoute: InsightsRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProgramsRoute: ProgramsRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
