/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesTalentAssessmentRouteImport } from './routes/services.talent-assessment'
import { Route as ServicesSoftSkillsRouteImport } from './routes/services.soft-skills'
import { Route as ServicesSalesCapabilityRouteImport } from './routes/services.sales-capability'
import { Route as ServicesLeadershipManagerialRouteImport } from './routes/services.leadership-managerial'
import { Route as ServicesFacilitatorDigitalLearningRouteImport } from './routes/services.facilitator-digital-learning'
import { Route as ServicesBusinessConsultingRouteImport } from './routes/services.business-consulting'
import { Route as ProductsLearningToPerformanceRouteImport } from './routes/products.learning-to-performance'
import { Route as ProductsCrmActRouteImport } from './routes/products.crm-act'
import { Route as ProductsAssessmentToolsRouteImport } from './routes/products.assessment-tools'
import { Route as InsightsWhitepapersRouteImport } from './routes/insights.whitepapers'
import { Route as InsightsWebinarsRouteImport } from './routes/insights.webinars'
import { Route as InsightsNewsRouteImport } from './routes/insights.news'
import { Route as InsightsArticlesRouteImport } from './routes/insights.articles'
import { Route as ClientsSuccessStoriesRouteImport } from './routes/clients.success-stories'
import { Route as ClientsPartnersRouteImport } from './routes/clients.partners'
import { Route as ClientsLearningImpactRouteImport } from './routes/clients.learning-impact'
import { Route as ClientsIndustriesRouteImport } from './routes/clients.industries'
import { Route as AboutWhoWeAreRouteImport } from './routes/about.who-we-are'
import { Route as AboutVisionMissionRouteImport } from './routes/about.vision-mission'
import { Route as AboutOurJourneyRouteImport } from './routes/about.our-journey'
import { Route as AboutOurApproachRouteImport } from './routes/about.our-approach'
import { Route as AboutLeadershipFacilitatorsRouteImport } from './routes/about.leadership-facilitators'
import { Route as AboutCoreValuesRouteImport } from './routes/about.core-values'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTalentAssessmentRoute =
  ServicesTalentAssessmentRouteImport.update({
    id: '/talent-assessment',
    path: '/talent-assessment',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSoftSkillsRoute = ServicesSoftSkillsRouteImport.update({
  id: '/soft-skills',
  path: '/soft-skills',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSalesCapabilityRoute = ServicesSalesCapabilityRouteImport.update({
  id: '/sales-capability',
  path: '/sales-capability',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLeadershipManagerialRoute =
  ServicesLeadershipManagerialRouteImport.update({
    id: '/leadership-managerial',
    path: '/leadership-managerial',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesFacilitatorDigitalLearningRoute =
  ServicesFacilitatorDigitalLearningRouteImport.update({
    id: '/facilitator-digital-learning',
    path: '/facilitator-digital-learning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesBusinessConsultingRoute =
  ServicesBusinessConsultingRouteImport.update({
    id: '/business-consulting',
    path: '/business-consulting',
    getParentRoute: () => ServicesRoute,
  } as any)
const ProductsLearningToPerformanceRoute =
  ProductsLearningToPerformanceRouteImport.update({
    id: '/learning-to-performance',
    path: '/learning-to-performance',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsCrmActRoute = ProductsCrmActRouteImport.update({
  id: '/crm-act',
  path: '/crm-act',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsAssessmentToolsRoute = ProductsAssessmentToolsRouteImport.update({
  id: '/assessment-tools',
  path: '/assessment-tools',
  getParentRoute: () => ProductsRoute,
} as any)
const InsightsWhitepapersRoute = InsightsWhitepapersRouteImport.update({
  id: '/whitepapers',
  path: '/whitepapers',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsWebinarsRoute = InsightsWebinarsRouteImport.update({
  id: '/webinars',
  path: '/webinars',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsNewsRoute = InsightsNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsArticlesRoute = InsightsArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => InsightsRoute,
} as any)
const ClientsSuccessStoriesRoute = ClientsSuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsPartnersRoute = ClientsPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsLearningImpactRoute = ClientsLearningImpactRouteImport.update({
  id: '/learning-impact',
  path: '/learning-impact',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsIndustriesRoute = ClientsIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => ClientsRoute,
} as any)
const AboutWhoWeAreRoute = AboutWhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => AboutRoute,
} as any)
const AboutVisionMissionRoute = AboutVisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => AboutRoute,
} as any)
const AboutOurJourneyRoute = AboutOurJourneyRouteImport.update({
  id: '/our-journey',
  path: '/our-journey',
  getParentRoute: () => AboutRoute,
} as any)
const AboutOurApproachRoute = AboutOurApproachRouteImport.update({
  id: '/our-approach',
  path: '/our-approach',
  getParentRoute: () => AboutRoute,
} as any)
const AboutLeadershipFacilitatorsRoute =
  AboutLeadershipFacilitatorsRouteImport.update({
    id: '/leadership-facilitators',
    path: '/leadership-facilitators',
    getParentRoute: () => AboutRoute,
  } as any)
const AboutCoreValuesRoute = AboutCoreValuesRouteImport.update({
  id: '/core-values',
  path: '/core-values',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/about/core-values': typeof AboutCoreValuesRoute
  '/about/leadership-facilitators': typeof AboutLeadershipFacilitatorsRoute
  '/about/our-approach': typeof AboutOurApproachRoute
  '/about/our-journey': typeof AboutOurJourneyRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/clients/industries': typeof ClientsIndustriesRoute
  '/clients/learning-impact': typeof ClientsLearningImpactRoute
  '/clients/partners': typeof ClientsPartnersRoute
  '/clients/success-stories': typeof ClientsSuccessStoriesRoute
  '/insights/articles': typeof InsightsArticlesRoute
  '/insights/news': typeof InsightsNewsRoute
  '/insights/webinars': typeof InsightsWebinarsRoute
  '/insights/whitepapers': typeof InsightsWhitepapersRoute
  '/products/assessment-tools': typeof ProductsAssessmentToolsRoute
  '/products/crm-act': typeof ProductsCrmActRoute
  '/products/learning-to-performance': typeof ProductsLearningToPerformanceRoute
  '/services/business-consulting': typeof ServicesBusinessConsultingRoute
  '/services/facilitator-digital-learning': typeof ServicesFacilitatorDigitalLearningRoute
  '/services/leadership-managerial': typeof ServicesLeadershipManagerialRoute
  '/services/sales-capability': typeof ServicesSalesCapabilityRoute
  '/services/soft-skills': typeof ServicesSoftSkillsRoute
  '/services/talent-assessment': typeof ServicesTalentAssessmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/about/core-values': typeof AboutCoreValuesRoute
  '/about/leadership-facilitators': typeof AboutLeadershipFacilitatorsRoute
  '/about/our-approach': typeof AboutOurApproachRoute
  '/about/our-journey': typeof AboutOurJourneyRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/clients/industries': typeof ClientsIndustriesRoute
  '/clients/learning-impact': typeof ClientsLearningImpactRoute
  '/clients/partners': typeof ClientsPartnersRoute
  '/clients/success-stories': typeof ClientsSuccessStoriesRoute
  '/insights/articles': typeof InsightsArticlesRoute
  '/insights/news': typeof InsightsNewsRoute
  '/insights/webinars': typeof InsightsWebinarsRoute
  '/insights/whitepapers': typeof InsightsWhitepapersRoute
  '/products/assessment-tools': typeof ProductsAssessmentToolsRoute
  '/products/crm-act': typeof ProductsCrmActRoute
  '/products/learning-to-performance': typeof ProductsLearningToPerformanceRoute
  '/services/business-consulting': typeof ServicesBusinessConsultingRoute
  '/services/facilitator-digital-learning': typeof ServicesFacilitatorDigitalLearningRoute
  '/services/leadership-managerial': typeof ServicesLeadershipManagerialRoute
  '/services/sales-capability': typeof ServicesSalesCapabilityRoute
  '/services/soft-skills': typeof ServicesSoftSkillsRoute
  '/services/talent-assessment': typeof ServicesTalentAssessmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/about/core-values': typeof AboutCoreValuesRoute
  '/about/leadership-facilitators': typeof AboutLeadershipFacilitatorsRoute
  '/about/our-approach': typeof AboutOurApproachRoute
  '/about/our-journey': typeof AboutOurJourneyRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/clients/industries': typeof ClientsIndustriesRoute
  '/clients/learning-impact': typeof ClientsLearningImpactRoute
  '/clients/partners': typeof ClientsPartnersRoute
  '/clients/success-stories': typeof ClientsSuccessStoriesRoute
  '/insights/articles': typeof InsightsArticlesRoute
  '/insights/news': typeof InsightsNewsRoute
  '/insights/webinars': typeof InsightsWebinarsRoute
  '/insights/whitepapers': typeof InsightsWhitepapersRoute
  '/products/assessment-tools': typeof ProductsAssessmentToolsRoute
  '/products/crm-act': typeof ProductsCrmActRoute
  '/products/learning-to-performance': typeof ProductsLearningToPerformanceRoute
  '/services/business-consulting': typeof ServicesBusinessConsultingRoute
  '/services/facilitator-digital-learning': typeof ServicesFacilitatorDigitalLearningRoute
  '/services/leadership-managerial': typeof ServicesLeadershipManagerialRoute
  '/services/sales-capability': typeof ServicesSalesCapabilityRoute
  '/services/soft-skills': typeof ServicesSoftSkillsRoute
  '/services/talent-assessment': typeof ServicesTalentAssessmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/impact'
    | '/insights'
    | '/privacy'
    | '/products'
    | '/programs'
    | '/services'
    | '/terms'
    | '/about/core-values'
    | '/about/leadership-facilitators'
    | '/about/our-approach'
    | '/about/our-journey'
    | '/about/vision-mission'
    | '/about/who-we-are'
    | '/clients/industries'
    | '/clients/learning-impact'
    | '/clients/partners'
    | '/clients/success-stories'
    | '/insights/articles'
    | '/insights/news'
    | '/insights/webinars'
    | '/insights/whitepapers'
    | '/products/assessment-tools'
    | '/products/crm-act'
    | '/products/learning-to-performance'
    | '/services/business-consulting'
    | '/services/facilitator-digital-learning'
    | '/services/leadership-managerial'
    | '/services/sales-capability'
    | '/services/soft-skills'
    | '/services/talent-assessment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/impact'
    | '/insights'
    | '/privacy'
    | '/products'
    | '/programs'
    | '/services'
    | '/terms'
    | '/about/core-values'
    | '/about/leadership-facilitators'
    | '/about/our-approach'
    | '/about/our-journey'
    | '/about/vision-mission'
    | '/about/who-we-are'
    | '/clients/industries'
    | '/clients/learning-impact'
    | '/clients/partners'
    | '/clients/success-stories'
    | '/insights/articles'
    | '/insights/news'
    | '/insights/webinars'
    | '/insights/whitepapers'
    | '/products/assessment-tools'
    | '/products/crm-act'
    | '/products/learning-to-performance'
    | '/services/business-consulting'
    | '/services/facilitator-digital-learning'
    | '/services/leadership-managerial'
    | '/services/sales-capability'
    | '/services/soft-skills'
    | '/services/talent-assessment'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clients'
    | '/contact'
    | '/impact'
    | '/insights'
    | '/privacy'
    | '/products'
    | '/programs'
    | '/services'
    | '/terms'
    | '/about/core-values'
    | '/about/leadership-facilitators'
    | '/about/our-approach'
    | '/about/our-journey'
    | '/about/vision-mission'
    | '/about/who-we-are'
    | '/clients/industries'
    | '/clients/learning-impact'
    | '/clients/partners'
    | '/clients/success-stories'
    | '/insights/articles'
    | '/insights/news'
    | '/insights/webinars'
    | '/insights/whitepapers'
    | '/products/assessment-tools'
    | '/products/crm-act'
    | '/products/learning-to-performance'
    | '/services/business-consulting'
    | '/services/facilitator-digital-learning'
    | '/services/leadership-managerial'
    | '/services/sales-capability'
    | '/services/soft-skills'
    | '/services/talent-assessment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  ContactRoute: typeof ContactRoute
  ImpactRoute: typeof ImpactRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProgramsRoute: typeof ProgramsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/talent-assessment': {
      id: '/services/talent-assessment'
      path: '/talent-assessment'
      fullPath: '/services/talent-assessment'
      preLoaderRoute: typeof ServicesTalentAssessmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/soft-skills': {
      id: '/services/soft-skills'
      path: '/soft-skills'
      fullPath: '/services/soft-skills'
      preLoaderRoute: typeof ServicesSoftSkillsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/sales-capability': {
      id: '/services/sales-capability'
      path: '/sales-capability'
      fullPath: '/services/sales-capability'
      preLoaderRoute: typeof ServicesSalesCapabilityRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/leadership-managerial': {
      id: '/services/leadership-managerial'
      path: '/leadership-managerial'
      fullPath: '/services/leadership-managerial'
      preLoaderRoute: typeof ServicesLeadershipManagerialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/facilitator-digital-learning': {
      id: '/services/facilitator-digital-learning'
      path: '/facilitator-digital-learning'
      fullPath: '/services/facilitator-digital-learning'
      preLoaderRoute: typeof ServicesFacilitatorDigitalLearningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/business-consulting': {
      id: '/services/business-consulting'
      path: '/business-consulting'
      fullPath: '/services/business-consulting'
      preLoaderRoute: typeof ServicesBusinessConsultingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/products/learning-to-performance': {
      id: '/products/learning-to-performance'
      path: '/learning-to-performance'
      fullPath: '/products/learning-to-performance'
      preLoaderRoute: typeof ProductsLearningToPerformanceRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/crm-act': {
      id: '/products/crm-act'
      path: '/crm-act'
      fullPath: '/products/crm-act'
      preLoaderRoute: typeof ProductsCrmActRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/assessment-tools': {
      id: '/products/assessment-tools'
      path: '/assessment-tools'
      fullPath: '/products/assessment-tools'
      preLoaderRoute: typeof ProductsAssessmentToolsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/insights/whitepapers': {
      id: '/insights/whitepapers'
      path: '/whitepapers'
      fullPath: '/insights/whitepapers'
      preLoaderRoute: typeof InsightsWhitepapersRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/webinars': {
      id: '/insights/webinars'
      path: '/webinars'
      fullPath: '/insights/webinars'
      preLoaderRoute: typeof InsightsWebinarsRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/news': {
      id: '/insights/news'
      path: '/news'
      fullPath: '/insights/news'
      preLoaderRoute: typeof InsightsNewsRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/articles': {
      id: '/insights/articles'
      path: '/articles'
      fullPath: '/insights/articles'
      preLoaderRoute: typeof InsightsArticlesRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/clients/success-stories': {
      id: '/clients/success-stories'
      path: '/success-stories'
      fullPath: '/clients/success-stories'
      preLoaderRoute: typeof ClientsSuccessStoriesRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/partners': {
      id: '/clients/partners'
      path: '/partners'
      fullPath: '/clients/partners'
      preLoaderRoute: typeof ClientsPartnersRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/learning-impact': {
      id: '/clients/learning-impact'
      path: '/learning-impact'
      fullPath: '/clients/learning-impact'
      preLoaderRoute: typeof ClientsLearningImpactRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/industries': {
      id: '/clients/industries'
      path: '/industries'
      fullPath: '/clients/industries'
      preLoaderRoute: typeof ClientsIndustriesRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/about/who-we-are': {
      id: '/about/who-we-are'
      path: '/who-we-are'
      fullPath: '/about/who-we-are'
      preLoaderRoute: typeof AboutWhoWeAreRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/vision-mission': {
      id: '/about/vision-mission'
      path: '/vision-mission'
      fullPath: '/about/vision-mission'
      preLoaderRoute: typeof AboutVisionMissionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/our-journey': {
      id: '/about/our-journey'
      path: '/our-journey'
      fullPath: '/about/our-journey'
      preLoaderRoute: typeof AboutOurJourneyRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/our-approach': {
      id: '/about/our-approach'
      path: '/our-approach'
      fullPath: '/about/our-approach'
      preLoaderRoute: typeof AboutOurApproachRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/leadership-facilitators': {
      id: '/about/leadership-facilitators'
      path: '/leadership-facilitators'
      fullPath: '/about/leadership-facilitators'
      preLoaderRoute: typeof AboutLeadershipFacilitatorsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/core-values': {
      id: '/about/core-values'
      path: '/core-values'
      fullPath: '/about/core-values'
      preLoaderRoute: typeof AboutCoreValuesRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutCoreValuesRoute: typeof AboutCoreValuesRoute
  AboutLeadershipFacilitatorsRoute: typeof AboutLeadershipFacilitatorsRoute
  AboutOurApproachRoute: typeof AboutOurApproachRoute
  AboutOurJourneyRoute: typeof AboutOurJourneyRoute
  AboutVisionMissionRoute: typeof AboutVisionMissionRoute
  AboutWhoWeAreRoute: typeof AboutWhoWeAreRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutCoreValuesRoute: AboutCoreValuesRoute,
  AboutLeadershipFacilitatorsRoute: AboutLeadershipFacilitatorsRoute,
  AboutOurApproachRoute: AboutOurApproachRoute,
  AboutOurJourneyRoute: AboutOurJourneyRoute,
  AboutVisionMissionRoute: AboutVisionMissionRoute,
  AboutWhoWeAreRoute: AboutWhoWeAreRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface ClientsRouteChildren {
  ClientsIndustriesRoute: typeof ClientsIndustriesRoute
  ClientsLearningImpactRoute: typeof ClientsLearningImpactRoute
  ClientsPartnersRoute: typeof ClientsPartnersRoute
  ClientsSuccessStoriesRoute: typeof ClientsSuccessStoriesRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIndustriesRoute: ClientsIndustriesRoute,
  ClientsLearningImpactRoute: ClientsLearningImpactRoute,
  ClientsPartnersRoute: ClientsPartnersRoute,
  ClientsSuccessStoriesRoute: ClientsSuccessStoriesRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface InsightsRouteChildren {
  InsightsArticlesRoute: typeof InsightsArticlesRoute
  InsightsNewsRoute: typeof InsightsNewsRoute
  InsightsWebinarsRoute: typeof InsightsWebinarsRoute
  InsightsWhitepapersRoute: typeof InsightsWhitepapersRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsArticlesRoute: InsightsArticlesRoute,
  InsightsNewsRoute: InsightsNewsRoute,
  InsightsWebinarsRoute: InsightsWebinarsRoute,
  InsightsWhitepapersRoute: InsightsWhitepapersRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface ProductsRouteChildren {
  ProductsAssessmentToolsRoute: typeof ProductsAssessmentToolsRoute
  ProductsCrmActRoute: typeof ProductsCrmActRoute
  ProductsLearningToPerformanceRoute: typeof ProductsLearningToPerformanceRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsAssessmentToolsRoute: ProductsAssessmentToolsRoute,
  ProductsCrmActRoute: ProductsCrmActRoute,
  ProductsLearningToPerformanceRoute: ProductsLearningToPerformanceRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesBusinessConsultingRoute: typeof ServicesBusinessConsultingRoute
  ServicesFacilitatorDigitalLearningRoute: typeof ServicesFacilitatorDigitalLearningRoute
  ServicesLeadershipManagerialRoute: typeof ServicesLeadershipManagerialRoute
  ServicesSalesCapabilityRoute: typeof ServicesSalesCapabilityRoute
  ServicesSoftSkillsRoute: typeof ServicesSoftSkillsRoute
  ServicesTalentAssessmentRoute: typeof ServicesTalentAssessmentRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBusinessConsultingRoute: ServicesBusinessConsultingRoute,
  ServicesFacilitatorDigitalLearningRoute:
    ServicesFacilitatorDigitalLearningRoute,
  ServicesLeadershipManagerialRoute: ServicesLeadershipManagerialRoute,
  ServicesSalesCapabilityRoute: ServicesSalesCapabilityRoute,
  ServicesSoftSkillsRoute: ServicesSoftSkillsRoute,
  ServicesTalentAssessmentRoute: ServicesTalentAssessmentRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  ContactRoute: ContactRoute,
  ImpactRoute: ImpactRoute,
  InsightsRoute: InsightsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProgramsRoute: ProgramsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
